eureka:
  client:
    # 注明自己的服务注册中心的地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    # 重要：以后的服务与服务之间相互调用一般都是根据这个name
    name: service-hi